import { AGENTS, PLATFORMS } from './domain.js';
import { opportunities, insights } from './seed.js';
import { runCampaignFromOpportunity } from './agents.js';
import { connectorStatus } from './connectors.js';
import { approveCampaign, regenerateHook, rejectCampaign, scheduleCampaign, simulatePublish } from './workflow.js';
import { AI_INTEGRATIONS, VIDEO_INTEGRATIONS, VOICE_INTEGRATIONS, STORAGE_INTEGRATIONS, isPaidIntegration } from './integration-registry.js';
import { load, save, reset } from './store.js';

let state=load(); let route=(location.hash||'#mission').slice(1); let busy=false;
const root=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const nav=[['mission','Mission Control'],['discover','Discover'],['studio','Studio'],['review','Approval'],['calendar','Calendar'],['publishing','Publishing'],['growth','Growth'],['settings','Integrations']];
const badge=s=>`<span class="badge">${esc(String(s).replaceAll('_',' '))}</span>`;
function shell(content){return `<div class="shell"><aside><div class="brand"><i>A</i><div><b>AUREXO</b><small>AI MEDIA OS</small></div></div><nav>${nav.map(([r,n])=>`<a href="#${r}" class="${route===r?'active':''}">${n}</a>`).join('')}</nav><div class="foot"><span></span> ${state.settings.zeroCostLock?'Zero-Cost Lock ON':'Paid fallback allowed'}<small>${esc(state.settings.niche)}</small></div></aside><main><header><div><small>AUREXO / ${nav.find(x=>x[0]===route)?.[1]||'Mission Control'}</small><h1>${route==='mission'?'Your AI media team is ready.':nav.find(x=>x[0]===route)?.[1]}</h1></div><button class="ghost" data-action="pause">Pause</button></header>${content}</main></div>`}
function metric(label,value,note){return `<div class="metric"><small>${label}</small><b>${value}</b><span>${note}</span></div>`}
function campaign(c){return `<article class="campaign"><div><small>${esc(c.category)}</small><h3>${esc(c.title)}</h3></div>${badge(c.state)}<p>${esc(c.strategy?.angle||'Campaign workflow in progress')}</p><div class="row"><span>Quality ${c.quality?.score??'—'}</span><span>${c.render?.provider||'Planning'}</span><span>₹${c.cost?.estimated??0}</span></div></article>`}
function mission(){const waiting=state.campaigns.filter(c=>c.state==='AWAITING_APPROVAL').length;return shell(`<section class="hero"><div><span class="eyebrow">PERSONAL AI SOCIAL STUDIO</span><h2>Discover. Create.<br><em>Approve. Grow.</em></h2><p>One control room for YouTube, Instagram and Facebook. AUREXO defaults to free-first AI and hybrid production, while premium providers stay optional.</p><button class="primary" data-action="generate">${busy?'Agents working…':'Generate Today’s Campaign'}</button></div><div class="orb">A<small>16 AGENTS</small></div></section><section class="metrics">${metric('CAMPAIGNS',state.campaigns.length,'created locally')}${metric('APPROVALS',waiting,'need your decision')}${metric('MONTH COST',`₹${state.spend.month}`,'estimated')}${metric('MODE',state.settings.budgetMode,state.settings.zeroCostLock?'zero-cost protected':'paid allowed')}</section><div class="grid"><section class="panel"><div class="head"><div><small>PRODUCTION</small><h3>Recent campaigns</h3></div><a href="#studio">Open Studio →</a></div>${state.campaigns.length?state.campaigns.slice(0,3).map(campaign).join(''):'<div class="empty">No campaigns yet. Generate the first one.</div>'}</section><section class="panel"><small>AI TEAM</small><h3>16 coordinated agents</h3><div class="agents">${AGENTS.map(a=>`<span title="${esc(a[1])}">${esc(a[0])}</span>`).join('')}</div><small>LEARNING SIGNALS</small>${insights.map(x=>`<p class="insight">${esc(x)}</p>`).join('')}</section></div>`)}
function discover(){return shell(`<section class="title"><span class="eyebrow">OPPORTUNITY ENGINE</span><h2>What should AUREXO make next?</h2><p>Demo opportunities prove the workflow today. Live trends plug into the secure backend later.</p></section><div class="cards">${opportunities.map(o=>`<article class="opp"><strong>${o.score}</strong><span>${esc(o.category)}</span><h3>${esc(o.title)}</h3><p>${esc(o.why)}</p><div class="row"><span>Fresh ${o.freshness}</span><span>Fit ${o.audienceFit}</span><span>Visual ${o.visual}</span></div><button class="secondary" data-action="generate-one" data-id="${o.id}">Build campaign</button></article>`).join('')}</div>`)}
function studio(){return shell(`<section class="title"><span class="eyebrow">PRODUCTION PIPELINE</span><h2>Studio</h2><p>Research → verify → strategy → script → scenes → platform variants → quality gate.</p></section>${state.campaigns.length?state.campaigns.map(c=>`<section class="panel studio">${campaign(c)}${c.script?`<div class="script"><small>HOOK</small><blockquote>${esc(c.script.hook)}</blockquote><p>${esc(c.script.body)}</p></div>`:''}${c.scenePlan?`<div class="timeline">${c.scenePlan.map(s=>`<div><b>${s.time}</b><span>${esc(s.type)}</span><p>${esc(s.visual)}</p></div>`).join('')}</div>`:''}${c.variants?`<div class="variants">${Object.entries(c.variants).map(([p,v])=>`<article><small>${p.toUpperCase()}</small><h4>${esc(v.title)}</h4><p>${esc(v.caption)}</p></article>`).join('')}</div>`:''}</section>`).join(''):'<section class="panel empty">Generate a campaign from Mission Control or Discover.</section>'}`)}
function review(){const q=state.campaigns.filter(c=>c.state==='AWAITING_APPROVAL');return shell(`<section class="title"><span class="eyebrow">HUMAN CONTROL</span><h2>Approval Queue</h2><p>Nothing reaches a real social account without your approval while approval mode is enabled.</p></section>${q.length?q.map(c=>`<section class="panel review">${campaign(c)}<div class="actions"><button class="ghost" data-action="reject" data-id="${c.id}">Reject</button><button class="secondary" data-action="regenerate" data-id="${c.id}">New hook</button><button class="primary" data-action="approve" data-id="${c.id}">Approve</button></div></section>`).join(''):'<section class="panel empty">No campaigns waiting for approval.</section>'}`)}
function calendar(){const scheduled=state.campaigns.filter(c=>['SCHEDULED','PUBLISHED'].includes(c.state));return shell(`<section class="title"><span class="eyebrow">CONTENT PLAN</span><h2>Calendar</h2></section><section class="panel">${scheduled.length?scheduled.map(c=>`<div class="cal"><b>${new Date(c.scheduledAt||c.publishedAt).toLocaleString()}</b>${campaign(c)}</div>`).join(''):'<div class="empty">Approved campaigns can be scheduled from Publishing.</div>'}</section>`)}
function publishing(){const cons=connectorStatus(state.settings); const jobs=state.campaigns.filter(c=>['APPROVED','SCHEDULED','PUBLISHED'].includes(c.state));return shell(`<section class="title"><span class="eyebrow">SOCIAL CONNECTORS</span><h2>Publishing Hub</h2><p>The buttons below simulate connection state until secure OAuth is connected. AUREXO never pretends a real post succeeded.</p></section><div class="connectors">${cons.map(c=>`<article><div class="logo">${c.id[0].toUpperCase()}</div><h3>${c.id}</h3>${badge(c.status)}<p>${esc(c.notes)}</p><button class="secondary" data-action="toggle-connect" data-id="${c.id}">${c.status==='connected'?'Disconnect demo':'Connect demo'}</button></article>`).join('')}</div><section class="panel"><small>PUBLISH JOBS</small>${jobs.length?jobs.map(c=>`<div class="job">${campaign(c)}${c.state==='APPROVED'?`<button class="primary" data-action="schedule" data-id="${c.id}">Schedule</button>`:''}${c.state==='SCHEDULED'?`<button class="primary" data-action="publish" data-id="${c.id}">Run safe publish simulation</button>`:''}</div>`).join(''):'<div class="empty">Approve a campaign first.</div>'}</section>`)}
function growth(){return shell(`<section class="title"><span class="eyebrow">EVIDENCE LOOP</span><h2>Growth Intelligence</h2><p>Real analytics will populate here after social APIs are connected.</p></section><section class="metrics">${PLATFORMS.map(p=>metric(p.toUpperCase(),state.growth[p].followers,'followers/subscribers')).join('')}${metric('LEARNED',state.campaigns.filter(c=>c.state==='LEARNED').length,'campaigns')}</section><section class="panel"><small>CURRENT RECOMMENDATIONS</small>${insights.map(x=>`<p class="insight">${esc(x)}</p>`).join('')}</section>`)}
function integrationRows(group,list){const flags=state.settings.integrationFlags[group];return list.map(v=>{const blocked=state.settings.zeroCostLock&&isPaidIntegration(v);return `<article class="provider ${blocked?'blocked':''}"><div><h4>${esc(v.name)} <span>${esc(v.tier)}</span></h4><p>${esc(v.note)}</p><small>${v.env.length?'Server slot: '+esc(v.env.join(', ')):'No secret required'}${blocked?' · blocked by Zero-Cost Lock':''}</small></div><label class="switch"><input type="checkbox" data-group="${group}" data-id="${v.id}" ${flags[v.id]?'checked':''} ${blocked?'disabled':''}><i></i></label></article>`}).join('')}
function settings(){return shell(`<section class="title"><span class="eyebrow">FREE-FIRST ROUTING</span><h2>Integrations & Cost Controls</h2><p>All paid providers are optional and OFF by default. API secrets belong in the secure backend, never this browser.</p></section><div class="settings"><section class="panel"><label class="toggle"><input type="checkbox" data-setting="zeroCostLock" ${state.settings.zeroCostLock?'checked':''}><b>Zero-Cost Lock</b><span>Hard-block paid providers even if configured.</span></label><label>Budget mode<select data-setting="budgetMode">${['Economy','Balanced','Premium'].map(x=>`<option ${state.settings.budgetMode===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Monthly budget ₹<input type="number" data-setting="monthlyBudget" value="${state.settings.monthlyBudget}"></label></section><section class="panel"><small>AI BRAIN</small>${integrationRows('ai',AI_INTEGRATIONS)}</section><section class="panel"><small>VIDEO</small>${integrationRows('video',VIDEO_INTEGRATIONS)}</section><section class="panel"><small>VOICE</small>${integrationRows('voice',VOICE_INTEGRATIONS)}</section><section class="panel"><small>STORAGE</small>${integrationRows('storage',STORAGE_INTEGRATIONS)}</section><section class="panel"><button class="ghost danger" data-action="reset">Reset local data</button></section></div>`)}
function render(){const pages={mission,discover,studio,review,calendar,publishing,growth,settings};root.innerHTML=(pages[route]||mission)();bind()}
function persist(){save(state);render()}
async function generate(opp){if(busy)return;busy=true;render();try{const c=await runCampaignFromOpportunity(opp,state.settings,live=>{const i=state.campaigns.findIndex(x=>x.id===live.id);if(i<0)state.campaigns.unshift(live);else state.campaigns[i]=live;save(state);render()});const i=state.campaigns.findIndex(x=>x.id===c.id);state.campaigns[i]=c;state.spend.month+=c.cost?.estimated||0;state.spend.today+=c.cost?.estimated||0;save(state)}finally{busy=false;render()}}
function bind(){document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>{const a=el.dataset.action,id=el.dataset.id;if(a==='generate')return generate(opportunities[0]);if(a==='generate-one')return generate(opportunities.find(x=>x.id===id));const i=state.campaigns.findIndex(x=>x.id===id);if(a==='approve')state.campaigns[i]=approveCampaign(state.campaigns[i]);if(a==='regenerate')state.campaigns[i]=regenerateHook(state.campaigns[i]);if(a==='reject')state.campaigns[i]=rejectCampaign(state.campaigns[i]);if(a==='schedule')state.campaigns[i]=scheduleCampaign(state.campaigns[i]);if(a==='publish')state.campaigns[i]=simulatePublish(state.campaigns[i],state.settings.social);if(a==='toggle-connect')state.settings.social[id]=state.settings.social[id]==='connected'?'disconnected':'connected';if(a==='pause')alert('AUREXO is paused. No real external publishing is active in this frontend build.');if(a==='reset')state=reset();persist()});document.querySelectorAll('[data-setting]').forEach(el=>el.onchange=()=>{state.settings[el.dataset.setting]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;persist()});document.querySelectorAll('[data-group]').forEach(el=>el.onchange=()=>{state.settings.integrationFlags[el.dataset.group][el.dataset.id]=el.checked;persist()})}
addEventListener('hashchange',()=>{route=(location.hash||'#mission').slice(1);render()});render();
